behaviors:
  PuzzleAgent:
    trainer_type: ppo
    max_steps: 5_000_000  # Train long enough (increase if needed)
    time_horizon: 512     # Handles multiple steps before updating (good for puzzles)
    summary_freq: 10000   # Save stats every 10k steps
    keep_checkpoints: 5   # Save 5 recent checkpoints
    checkpoint_interval: 500_000

    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    self_play:
      save_steps: 0

    threaded: true
